cookie:
  expiry_days: 30
  key: health_hack_key
  name: health_hack_cookie
credentials:
  usernames:
    testuser:
      email: healthhack2024@gmail.com
      logged_in: false
      name: Test User
      password: healthhack
preauthorized:
  emails:
  - chen.wynne@gmail.com

